spring:
  datasource:
    username: yuseon
    password: yuseon
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_create: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.BasicBinder: TRACE
      springframework:
        security: DEBUG

pre-user:
  adminVariableId: admin@gmail.com
  adminPassword: admin
  userVariableId: user@gmail.com
  userPassword: user
  clientId: client@gmail.com
  clientSecret: client

---
spring:
  profiles: test
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
